# Generated by Django 5.1.6 on 2025-03-14 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssortmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва виробу')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assortment/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Асортимент',
                'verbose_name_plural': 'Асортимент',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('торт', 'Торт'), ('кекси', 'Кекси'), ('цукерки', 'Цукерки'), ('інше', 'Інше')], max_length=20, verbose_name='Тип виробу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('order_date', models.DateField(verbose_name='Дата замовлення')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я замовника")),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефону повинен бути в форматі: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254, verbose_name='Email замовника')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('новий', 'Новий'), ('прийнято', 'Прийнято'), ('виконується', 'Виконується'), ('готово', 'Готово'), ('доставлено', 'Доставлено')], default='новий', max_length=20, verbose_name='Статус замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
    ]
